
aggregation:
  application:
    config:
      topology:
        inputTopicName: intopic
        outputTopicName: outtopic
      kafka:
        properties:
          "[application.id]": "aggregator"
          "[bootstrap.servers]": "kafka-aggregation.default.svc.cluster.local:9092"
  image:
    repository: ghcr.io/jjrising/kafka-aggregation/aggregation
    tag: latest
  port: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
  serviceAccount:
    annotations: {}

#grafana:

kafka:
  provisioning:
    enabled: true
    numPartitions: 12
    topics:
      - name: intopic
        partitions: 12
        replicationFactor: 1
      - name: outtopic
        partitions: 12
        replicationFactor: 1

prometheus:
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
