
aggregation:
  enabled: true
  application:
    config:
      kafka-topology:
        inputTopicName: events
        aggregatedTopicName: aggregated-events
        lostTopicName: lost-events
        schemaRegistryBaseUrl: "http://schema-registry-headless.default.svc.cluster.local:8081"
        aggregation-processor:
          expiryProcessIntervalSeconds: 1
        properties:
          "[application.id]": "aggregator"
          "[bootstrap.servers]": "kafka.default.svc.cluster.local:9092"
          "[schema.registry.url]": "http://schema-registry-headless.default.svc.cluster.local:8081"
          "[auto.register.schemas]": true
  image:
    repository: ghcr.io/jjrising/kafka-aggregation/aggregation
    tag: latest
  port: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
  serviceAccount:
    annotations: {}

connector:
  enabled: true
  image:
    repository: ghcr.io/jjrising/kafka-aggregation/connector
    tag: latest
  env:
    - name: CONNECT_KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
  port: 8083
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
  groupId: aggregation-connector
  heapOptions: "-Xms512M -Xmx512M"

generator:
  enabled: false
  application:
    config:
      spring:
        kafka:
          bootstrap-servers: "kafka.default.svc.cluster.local:9092"
          producer:
            key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  image:
    repository: ghcr.io/jjrising/kafka-aggregation/generator
    tag: latest
  port: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
  serviceAccount:
    annotations: {}

#grafana:

kafka:
  fullnameOverride: "kafka"
  provisioning:
    enabled: true
    numPartitions: 12
    topics:
      - name: events
        partitions: 12
        replicationFactor: 1
      - name: aggregated-events
        partitions: 12
        replicationFactor: 1
      - name: lost-events
        partitions: 12
        replicationFactor: 1

prometheus:
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false

schema-registry:
  kafka:
    enabled: false
  fullnameOverride: "schema-registry"
  externalKafka:
    brokers:
      - PLAINTEXT://kafka-headless.default.svc.cluster.local:9092
