apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.aggregation.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-aggregation.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kafka-aggregation.fullname" . }}-aggregation
  template:
    metadata:
      labels:
        {{- include "kafka-aggregation.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafka-aggregation.fullname" . }}-aggregation
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: aggregation
          image: "{{ .Values.aggregation.image.repository }}:{{ .Values.aggregation.image.tag}}"
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.aggregation.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.aggregation.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-aggregation.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
  {{- with .Values.aggregation.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
data:
  {{- with .Values.aggregation.application.config }}
  application.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
