apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.aggregation.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-aggregation.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kafka-aggregation.fullname" . }}-aggregation
  template:
    metadata:
      labels:
        {{- include "kafka-aggregation.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafka-aggregation.serviceAccountName" . }}
      containers:
        - name: aggregation
          image: "{{ .Values.aggregation.image.repository }}:{{ .Values.aggregation.image.tag}}"
          imagePullPolicy: Always
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/liveness
              port: 8081
          readinessProbe:
            httpGet:
              path: /actuator/readiness
              port: 8081
          resources:
            {{- toYaml .Values.aggregation.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-aggregation.fullname" . }}-aggregation
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.aggregation.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-aggregation.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-aggregation.serviceAccountName" . }}
  labels:
    {{- include "kafka-aggregation.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
